language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - pypy
before_install:
  # ignore failed build on PyPy
  - python setup.py build || test "$TRAVIS_PYTHON_VERSION" == "pypy"
script:
  - python setup.py test